version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=${PG_USER:-barnamoyroy}
      - PG_PASSWORD=${PG_PASSWORD:-navy3121}
      - PG_DATABASE=${PG_DATABASE:-code_review}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USER:-barnamoyroy}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-navy3121}
      - POSTGRES_DB=${PG_DATABASE:-code_review}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: