name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set lowercase repository name
      run: |
        echo "REPO_LC=${REPO,,}" >> ${GITHUB_ENV}
      env:
        REPO: '${{ github.repository }}'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/ai-code-review:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/ai-code-review:${{ github.sha }}

    - name: Deploy to production
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Add your deployment commands here"
        # Example: Deploy to cloud platform of your choice
